### ISSUE TITLE
simplifying the symbolic expressions of the substitution sigma 

### ISSUE THREAD

**Issue by cavilacion** [zsusag/symbolic_semantics_of_probabilistic_programs#5]
The random walk produces results such as 
`sigma(u) = 0+0-1+1+0+0+0-1+0+0-1`
Can these expressions be simplified, since they contain only numbers?

**Comment by zsusag** [comment]
Absolutely! I have pushed the change that fixes it: c1b345ab95406fef5211be56e044a5537ddcb4c3

It is relatively rudimentary right now. It doesn't apply any properties such as associativity, commutativity, etc. It simply simplifies the expression tree if the children of a node are both constants (i.e., either a number or a boolean).
